# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestTest2():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test2(self):
        self.driver.get("https://www.baidu.com/")
        self.driver.set_window_size(1050, 840)
        self.driver.find_element(By.ID, "kw").send_keys("hello")
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "kw").click()
        # element = self.driver.find_element(By.LINK_TEXT, "hello_百度翻译")
        # actions = ActionChains(self.driver)
        # actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "kw").click()
        element = self.driver.find_element(By.ID, "kw")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "kw").send_keys("world")
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "kw").click()
        self.driver.find_element(By.ID, "kw").click()
        element = self.driver.find_element(By.ID, "kw")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "kw").send_keys("python")
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "kw").click()
        element = self.driver.find_element(By.ID, "kw")
        actions = ActionChains(self.driver)
        actions.double_click(element).perform()
        self.driver.find_element(By.ID, "kw").send_keys("java")
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)

